### PR TITLE
Add CORS config to nginx.

### LINKED ISSUE #296: Cross Origin support for infotip JSON file
Fabric8-ui net is likely to consume the infotip data from [here](https://docs.openshift.io/json/infotips.json), but this api is not cross origin supported. 

Solution: Add respective header to allow all origins.

### PR DESCRIPTION
**Pull request by rkratky**
To fix #296. Added CORS config directly to `nginx.conf`.

### CODE REVIEW

**Comment by fabric8cd** [comment]
@rkratky snapshot fabric8/fabric8-online-docs:SNAPSHOT-PR-314-2 is available for testing at http://fabric8-online-docs-app-pr-314-fabric8-online-docs.badger.fabric8.io

**Comment by rkratky** [comment]
Ha, it finally built. @divyanshiGupta, now it should be possible to test just with http://fabric8-online-docs-app-pr-314-fabric8-online-docs.badger.fabric8.io/json/infotips.json

**Comment by divyanshiGupta** [comment]
@rkratky I tested it and it's working. Can you tell me when this will be merged?

**Comment by rkratky** [comment]
Thanks, @divyanshiGupta -- merged now. Will push to prod ASAP.

**Comment by divyanshiGupta** [comment]
@rkratky the changes are still not in prod.

**Pull request merged**
