### PR TITLE
Substantial edits to ch1

### PR DESCRIPTION
**Pull request by mishaone**
* Renamed this because I think it makes more sense to talk about resetting the osio env instead of oso because that is what the user in our docs will be looking to do.
* Changed the formatting of the reasons since they looked like mini-headlines at the moment.
* Removed images that were not necessary (all of them)
* MInor structural changes to steps.

### CODE REVIEW

**Comment by mishaone** [comment]
@Preeticp if you have time, please have a look. This is just one module so shouldn't take much time.

**Comment by mishaone** [comment]
Good point, @Preeticp. I'll make the change in a new PR so it can get reviewed separately and merge this.

**Comment by mishaone** [comment]
I just had a look at this @Preeticp and I recall why it's where it is. This is ideally after Optimizing, BUT the sections after that are about analyzing the application and using the che workspace to learn advanced che features. These wouldn't be doable if we wiped our two quickstarts before this. Therefore, we leave those two quickstarts so that users can use the code for analyzing applications and che features and then tell people to wipe their osio environment.

**Comment by Preeticp** [comment]
Totally agree with that logic. Using the same logic, I wonder if it makes sense to move the entire optimizing resources to after the advanced Che section. The need to optimize your resources would occur only post the 2 quickstarts (Vertx and Springboot) are launched, modified and analyzed. WDYT?

**Comment by mishaone** [comment]
Yes, that's a really good idea. I'll implement that in the new PR instead. Thanks for the feedback, @Preeticp!

**Comment by Preeticp** [comment]
Ack @mishaone, I guess you meant commits from here: https://github.com/fabric8io/fabric8-online-docs/pull/419?
I am wondering what would be the best way? Forking your branch and getting your commits seems to be the way to go. @rkratky wdyt? Is there any other better way?
Most of the modules I need to work on are also part of this PR as they are reused in both sections. So I was waiting for #419 to get in so that I can pull these changes and then add my work.

**Pull request merged**
