### PR TITLE
Modified create work item topics as per latest UX.

### PR DESCRIPTION
**Pull request by Preeticp**
Post this, will be working on the 'Modifying your WI', and 'working with your WI' sections. Also updating the current 'About WIs' is WIP.
Gradually will streamline the flow once all topics are in.

### CODE REVIEW

**Comment by fabric8cd** [comment]
@Preeticp snapshot fabric8/fabric8-online-docs:SNAPSHOT-PR-194-4 is available for testing at http://fabric8-online-docs-app-pr-194-fabric8-online-docs.badger.fabric8.io

**Comment by Preeticp** [comment]
@rkratky can you please merge this, the validate and build scripts run fine.
I am unable to validate #195 because it references one of the topics deleted in this PR.

**Comment by rkratky** [comment]
@Preeticp I don't have time for a review today. Could you please arrange someone else to peer-review this PR?

**Comment by Preeticp** [comment]
@mishaone can you please review this and merge it if it is alright with you. Please note, I have changed the includes, as there is no separate detailed add in the Plan tab. (Keeping with 'documenting the most easiest way to do a task' thought). In the modifying the WI section I will capture the Analyze tab method. I will streamline all the includes as I add more topics to the WIs part.

**Comment by mishaone** [comment]
Sure, on it.

**Comment by mishaone** [comment]
Looks good to me. Merging and closing.

**Comment by Preeticp** [comment]
Thank you @mishaone

**Pull request merged**
