### PR TITLE
Updated deployments modules and tested everything. Also updated all s…

### PR DESCRIPTION
**Pull request by mishaone**
* Updated deployment content from before with updated screenshots and instructions (and testing)
* Updated commented out deployment content now that I can test it
* Updated all screenshots that deal with the profile menu, the new ? icon, and the tenant status.
This incorporates https://github.com/fabric8io/fabric8-online-docs/issues/173 and https://github.com/fabric8io/fabric8-online-docs/issues/184

### CODE REVIEW

**Comment by fabric8cd** [comment]
@mishaone snapshot fabric8/fabric8-online-docs:SNAPSHOT-PR-186-1 is available for testing at http://fabric8-online-docs-app-pr-186-fabric8-online-docs.badger.fabric8.io

**Comment by mishaone** [comment]
Robert, assigning review to you so you can have a quick look. Also, I would recommend that if this looks okay to you, we should push it to docs.os.io since the deployment part is a direct update to the untested and commented out content we pushed in a rush for Issue-173

**Comment by rkratky** [comment]
@mishaone, pushed to prod.

**Comment by mishaone** [comment]
Thanks!

**Pull request merged**
