### PR TITLE
#17 : Fix incorrect image URL in fabric8-online-docs.app.yaml

### PR DESCRIPTION
**Pull request by aditya-konarde**
Fix Image URL for fabric8-online-docs.
Fix typo in Template name
Issue #17

### CODE REVIEW

**Comment by fabric8cd** [comment]
@aditya-konarde snapshot fabric8/fabric8-online-docs:SNAPSHOT-PR-18-1 is available for testing at http://fabric8-online-docs-app-pr-18-fabric8-online-docs.badger.fabric8.io

**Comment by kbsingh** [comment]
needs some more consideration.

**Comment by kbsingh** [comment]
👍

**Comment by aditya-konarde** [comment]
@rkratky please have a look at this PR. We will need to merge this for the pipeline to work as expected.

**Comment by aditya-konarde** [comment]
@rkratky Can you please merge this?

**Pull request merged**
