### PR TITLE
[WIP] - Updated Spring Boot project chapter

### PR DESCRIPTION
**Pull request by mishaone**
* Fixing up Spring Boot chapter
* Need to wait till workspace issue is resolved in OSIO to test and update docs and screenshots for that part

### CODE REVIEW

**Comment by mishaone** [comment]
A weird remote issue has (re)occurred. Saving time and just merging this, which is just minor fixes to the SB part and adding the larger changes in the intro to a new PR.

**Comment by mishaone** [comment]
@rkratky - could you have a look at this and merge if it's okay? I have that annoying branch and remote tips being out of sync issue again and it's just faster to copy over the changes in a new PR once this is approved and merged.

**Comment by mishaone** [comment]
NVM, fixed the thing and added the new changes. Ignore that, Robert.

**Comment by rkratky** [comment]
@mishaone, FWIW, this PR builds fine and can be merged in its current state.

**Comment by mishaone** [comment]
Yep, thanks Robert. I had an error with the tip of the local branch being in a different place from the tip on the remote, which has happened before. Got steps to fix it now, plus was able to commit and push changes. I'll continue adding a few more changes to this PR and then request review.

**Comment by mishaone** [comment]
@rkratky - based on our email discussion after the meeting, can you confirm it's okay to merge this? After that's done, we can send links to the built document for review.

**Comment by mishaone** [comment]
Sorry about all the comments. It was useful to have the current (extensive changes) as a reference as I did more changes today so I continued working in this branch and committed to this PR. @rkratky can you do a quick review (nothing is broken/obviously wrong) and then merge if you approve? I'll update my local repo once this is merged and start a new PR from tomorrow. We will get review for the finished version of these changes once this is concluded so I don't think there is much of a reason to keep this open for now.

**Comment by Preeticp** [comment]
It makes sense to merge this PR so that I can start reviewing the doc as per the latest changes made by Misha. I began reviewing the prod preview version and realized that it was the old version.

**Pull request merged**
