### PR TITLE
Created assembly for resource usage in User guide

### LINKED ISSUE #398: Create new assembly for Resources section (follow up of PR #385)
As discussed in the meeting, club together 1. general resources info in OSIO, 2. detailed resource info in OC and then 3. cleaning OSIO account, into an assembly such as 'Monitoring your resources'.
Follow up action from PR #385 
Also, fix numbering issues with the resources section, refer #385

### PR DESCRIPTION
**Pull request by Preeticp**
This PR:
1. Combines all the modules related to resource usage and fixes #398 
2. Corrects numbering issues introduced in #385 
3. Adds relevant resource information to UG by removing conditionals where not necessary.

### CODE REVIEW

**Comment by Preeticp** [comment]
@mishaone, @rkratky these are my observations based on working on this PR as well as similar PRs before GA: 
1. Avoid conditionals unless really necessary, otherwise it defeats the purpose of reuse in Modular docs. I understand tone of voice necessitates it at times, but facts/absolute values do not need conditionals.
2. If you do use conditionals, build and validate to see there are no numbering issues introduced due to them. Most times, its just a matter of adding appropriate blank lines or making corrections to spacing.

In the current situation, conditionals were just not required as the Available Resources information was relevant to both the User Guide as well as the Getting Started. You cannot predict which doc a user prefers to refer.

**Comment by mishaone** [comment]
@Preeticp can you give us an example to use as context for conditionals not being necessary. If they aren't necessary, we should certainly not have them. I would disagree with them defeating the purpose of modular docs, since they allow us to single source (and update/change things in one place instead of multiple mildly different modules) content.

**Comment by Preeticp** [comment]
Builds and validates fine, merging this PR as it reorders existing modules into an assembly as agreed to in our meeting and fixes the numbering bug introduced in #385

**Comment by Preeticp** [comment]
@mishaone this sentence imo is relevant to both the guides hence use of conditional coud have been avoided here: The memory allowances for each OpenShift pod is 512{nbsp}MiB. As a result, each application consumes nearly 1{nbsp}GiB of memory for the *Stage* and *Run* environments.

**Comment by mishaone** [comment]
Sure, that's fair. In that case, we can just remove the conditionals. They are there to make reuse easier (and the flow less abrupt depending on how many places we're using the module).

**Pull request merged**
