### PR TITLE
Modified the create space, create application and import app sections…

### PR DESCRIPTION
**Pull request by Preeticp**
… as per latest on prod preview.
Things that are not yet on Prod preview are commented out.

### CODE REVIEW

**Comment by fabric8cd** [comment]
@Preeticp snapshot docs image is available. Try `docker pull quay.io/openshiftio/fabric8io-fabric8-online-docs:SNAPSHOT-PR-448-9`, run the image using `docker run -it -p 4000:8080 quay.io/openshiftio/fabric8io-fabric8-online-docs:SNAPSHOT-PR-448-9`. Docs are now available for preview at `http://127.0.0.1:4000` Thanks

**Comment by fabric8cd** [comment]
@Preeticp snapshot docs image is available. Try `docker pull quay.io/openshiftio/fabric8io-fabric8-online-docs:SNAPSHOT-PR-448-10`, run the image using `docker run -it -p 4000:8080 quay.io/openshiftio/fabric8io-fabric8-online-docs:SNAPSHOT-PR-448-10`. Docs are now available for preview at `http://127.0.0.1:4000` Thanks

**Comment by fabric8cd** [comment]
@Preeticp snapshot docs image is available. Try `docker pull quay.io/openshiftio/fabric8io-fabric8-online-docs:SNAPSHOT-PR-448-11`, run the image using `docker run -it -p 4000:8080 quay.io/openshiftio/fabric8io-fabric8-online-docs:SNAPSHOT-PR-448-11`. Docs are now available for preview at `http://127.0.0.1:4000` Thanks

**Comment by Preeticp** [comment]
Builds, verifies fine, note some of the changes(space creation flow in prod-preview only) are commented out these will need to be updated as soon as the UI features are pushed to Prod.

**Pull request merged**
