### PR TITLE
Test fixing Jenkinsfile

### PR DESCRIPTION
**Pull request by rkratky**

### CODE REVIEW

**Comment by rkratky** [comment]
@maxandersen, your #120 got me started, so I tried (in this PR) adding the required stuff to the Jenkinsfile (specifying the Dockerfile from which to build the image: `Dockerfile.deploy`).

The pipeline successfully built and pushed the container, but then it failed on deploy:

> Checking if user rkratky is a collaborator on fabric8/fabric8-online-docs
> Change author is not a collaborator on the project, aborting build until we support the [test] comment

Looks like I don't have the rights to change the Jenkinsfile. Could you please make me a 'collaborator'?

**Comment by maxandersen** [comment]
> Looks like I don't have the rights to change the Jenkinsfile. Could you please make me a 'collaborator'?

you are in the `docs` group which has write access so you should be all good - but let me try add you as collaborator directly to see if makes a difference.

**Comment by rkratky** [comment]
> you are in the docs group which has write access so you should be all good

If the problem really is with access rights, then this isn't enough.

> let me try add you as collaborator directly to see if makes a difference

@maxandersen, I tried adding one more step to the pipeline, and it works well, but it still fails on deploy. Same error message:

```
Checking if user rkratky is a collaborator on fabric8/fabric8-online-docs
Change author is not a collaborator on the project,
aborting build until we support the [test] comment— Error signal
```

**Comment by rawlingsj** [comment]
Look like the github repo is incorrect and therefore doesn't get the correct list of collaborators.  I.e. https://github.com/fabric8io/fabric8-online-docs/blob/master/Jenkinsfile#L81

should be `githubProject = 'fabric8io/fabric8-online-docs'`
and not     `githubProject = 'fabric8/fabric8-online-docs'`

**Comment by fabric8cd** [comment]
@rkratky snapshot fabric8/fabric8-online-docs:SNAPSHOT-PR-126-10 is available for testing at http://fabric8-online-docs-app-pr-126-fabric8-online-docs.badger.fabric8.io

**Pull request merged**
