### PR TITLE
[WIP] Screenshots updated for brand change and UI updates

### PR DESCRIPTION
**Pull request by Preeticp**
GS updated.
To Do:
UG

### CODE REVIEW

**Comment by fabric8cd** [comment]
@Preeticp snapshot docs image is available. Try `docker pull quay.io/openshiftio/fabric8io-fabric8-online-docs:SNAPSHOT-PR-465-28`, run the image using `docker run -it -p 4000:8080 quay.io/openshiftio/fabric8io-fabric8-online-docs:SNAPSHOT-PR-465-28`. Docs are now available for preview at `http://127.0.0.1:4000` Thanks

**Comment by fabric8cd** [comment]
@Preeticp snapshot docs image is available. Try `docker pull quay.io/openshiftio/fabric8io-fabric8-online-docs:SNAPSHOT-PR-465-30`, run the image using `docker run -it -p 4000:8080 quay.io/openshiftio/fabric8io-fabric8-online-docs:SNAPSHOT-PR-465-30`. Docs are now available for preview at `http://127.0.0.1:4000` Thanks

**Comment by fabric8cd** [comment]
@Preeticp snapshot docs image is available. Try `docker pull quay.io/openshiftio/fabric8io-fabric8-online-docs:SNAPSHOT-PR-465-31`, run the image using `docker run -it -p 4000:8080 quay.io/openshiftio/fabric8io-fabric8-online-docs:SNAPSHOT-PR-465-31`. Docs are now available for preview at `http://127.0.0.1:4000` Thanks

**Comment by Preeticp** [comment]
Fixed all references to OSIO in screenshots, both GSG and UG. Built and verified, merging now.

**Comment by fabric8cd** [comment]
@Preeticp snapshot docs image is available. Try `docker pull quay.io/openshiftio/fabric8io-fabric8-online-docs:SNAPSHOT-PR-465-32`, run the image using `docker run -it -p 4000:8080 quay.io/openshiftio/fabric8io-fabric8-online-docs:SNAPSHOT-PR-465-32`. Docs are now available for preview at `http://127.0.0.1:4000` Thanks

**Pull request merged**
