### PR TITLE
lets try and fix the builds

### PR DESCRIPTION
**Pull request by rawlingsj**

### CODE REVIEW

**Comment by rkratky** [comment]
Thanks @rawlingsj!

If at all possible, could you also please have a look at building from master? -- While PR builds are very convenient for us, it's the cherry on top. Builds from master (or any old branch) are crucial.

**Comment by rawlingsj** [comment]
@rkratky yeah its the same problem, once this PR works master will too

**Comment by fabric8cd** [comment]
@rawlingsj snapshot fabric8/fabric8-online-docs:SNAPSHOT-PR-7-4 is available for testing at http://fabric8-online-docs-app-pr-7-fabric8-online-docs.badger.fabric8.io

**Comment by rawlingsj** [comment]
@rkratky yay! sorted.  see link above.

**Comment by rkratky** [comment]
Awesome :-) Btw, will the build be discarded some time the PR is merged?

What's the URL for master?

**Comment by rawlingsj** [comment]
>What's the URL for master?

http://jenkins.cd.k8s.fabric8.io/job/auto/job/fabric8-online-docs/job/master/

and this is the app job which generates and releases the YAML.  The repo is automatically updated with the new version and triggered after the image above is built and pushed to docker hub http://jenkins.cd.k8s.fabric8.io/job/fabric8-apps/job/fabric8-online-docs-app/job/master/

**Comment by rawlingsj** [comment]
> Btw, will the build be discarded some time after the PR is merged?

yeah I think the old PR deployments get cleared up every 3 hours or so

**Comment by rkratky** [comment]
> http://jenkins.cd.k8s.fabric8.io/job/auto/job/fabric8-online-docs/job/master/

Apologies, what I meant was what's the URL of the rendered doc. I can't seem to figure it out from the Jenkins job.

**Comment by rawlingsj** [comment]
master is not deployed or running anywhere.   That's the other part of the email I sent, i.e. we have CI and CD pipelines but nowhere to deploy the released docs.  If you or someone can tell me where to deploy it I can add that into the pipeline.

Until then to test it out you can run https://github.com/fabric8io/fabric8-online-docs#deploying-the-documentation-on-openshift

**Comment by rkratky** [comment]
Got it, I misunderstood before. Unfortunately, I know next to nothing about the available infrastructure, but I can ask powers that be for assistance.

**Pull request merged**
