### PR TITLE
Issue 30e - continuing work on e2e doc

### PR DESCRIPTION
**Pull request by mishaone**
* Updated and reworked some content, added screenshots, details Todd wanted in doc, etc.

### CODE REVIEW

**Comment by rkratky** [comment]
@mishaone, is this ready to be reviewed? I see you assigned me for a review, but I'm confused by the `[WIP]` prefix.

**Comment by mishaone** [comment]
@rkratky, hi. I didn't assign this for review to anyone. I can see you listed under suggestions for reviewers, but not assigned, I think. The number of files changes are high, but the actual lines only about 120 since this is only about a day or so's work (and lots of added screenshots). I'll try to keep it to one PR a day, which should help bring that down further, hopefully.

**Comment by mishaone** [comment]
Since this is already larger than you wanted @rkratky, I'll go ahead and merge it. Just to clarify, we'll be doing a full review after this process is completed for the whole doc. The merging of PRs is just to track the updates and merge if nothing is broken (and let me include the changes in the next PR as I go).

**Comment by rkratky** [comment]
>  I didn't assign this for review to anyone. I can see you listed under suggestions for reviewers, but not assigned, I think. 

Ah, I misunderstood. 

> Since this is already larger than you wanted @rkratky, I'll go ahead and merge it. Just to clarify, we'll be doing a full review after this process is completed for the whole doc. 

OK. My main concern is that we make it as easy as possible for (potential) reviewers to go through the PRs. It would be great if the indiv. PRs could each touch only one area/topic or fix/update one particular issue.

**Pull request merged**
