### PR TITLE
New create space & app, pin spaces, s/project/codebase, Deleted redundant codebase modules & pngs

### LINKED ISSUE #461: Replace Project with Codebase in the import codebase flow, to keep it consistent with UI
Check entire GS and UG for the same, we add/import a codebase to create applications. Projects is ok to use in the planning sections to refer to an entire devp project.

### LINKED ISSUE #471: Adding space and app modal has changed

### LINKED ISSUE #472: Add info about ability to pin spaces in Spaces page

### PR DESCRIPTION
**Pull request by Preeticp**
Done:

- Cleaned up redundant codebases modules and images.
- Added more commented out instruction for app creation modal for first time users. Commented out because still in prod-preview not on prod.
- Update screenshots for create space and app workflows. Fixes #471 
- Replaced importing projects to importing codebases in all guides. Fixes #461 
- Added info about ability to pin spaces, but commented out since not yet on prod. Fixes #472 
- Deleted remnants of mention of Deployment screen, and improved a few images.

### CODE REVIEW

**Comment by fabric8cd** [comment]
@Preeticp snapshot docs image is available. Try `docker pull quay.io/openshiftio/fabric8io-fabric8-online-docs:SNAPSHOT-PR-473-37`, run the image using `docker run -it -p 4000:8080 quay.io/openshiftio/fabric8io-fabric8-online-docs:SNAPSHOT-PR-473-37`. Docs are now available for preview at `http://127.0.0.1:4000` Thanks

**Comment by fabric8cd** [comment]
@Preeticp snapshot docs image is available. Try `docker pull quay.io/openshiftio/fabric8io-fabric8-online-docs:SNAPSHOT-PR-473-39`, run the image using `docker run -it -p 4000:8080 quay.io/openshiftio/fabric8io-fabric8-online-docs:SNAPSHOT-PR-473-39`. Docs are now available for preview at `http://127.0.0.1:4000` Thanks

**Comment by fabric8cd** [comment]
@Preeticp snapshot docs image is available. Try `docker pull quay.io/openshiftio/fabric8io-fabric8-online-docs:SNAPSHOT-PR-473-40`, run the image using `docker run -it -p 4000:8080 quay.io/openshiftio/fabric8io-fabric8-online-docs:SNAPSHOT-PR-473-40`. Docs are now available for preview at `http://127.0.0.1:4000` Thanks

**Comment by fabric8cd** [comment]
@Preeticp snapshot docs image is available. Try `docker pull quay.io/openshiftio/fabric8io-fabric8-online-docs:SNAPSHOT-PR-473-41`, run the image using `docker run -it -p 4000:8080 quay.io/openshiftio/fabric8io-fabric8-online-docs:SNAPSHOT-PR-473-41`. Docs are now available for preview at `http://127.0.0.1:4000` Thanks

**Comment by fabric8cd** [comment]
@Preeticp snapshot docs image is available. Try `docker pull quay.io/openshiftio/fabric8io-fabric8-online-docs:SNAPSHOT-PR-473-42`, run the image using `docker run -it -p 4000:8080 quay.io/openshiftio/fabric8io-fabric8-online-docs:SNAPSHOT-PR-473-42`. Docs are now available for preview at `http://127.0.0.1:4000` Thanks

**Comment by fabric8cd** [comment]
@Preeticp snapshot docs image is available. Try `docker pull quay.io/openshiftio/fabric8io-fabric8-online-docs:SNAPSHOT-PR-473-43`, run the image using `docker run -it -p 4000:8080 quay.io/openshiftio/fabric8io-fabric8-online-docs:SNAPSHOT-PR-473-43`. Docs are now available for preview at `http://127.0.0.1:4000` Thanks

**Comment by Preeticp** [comment]
Reviewed and verified both locally and on snapshot. Merging now.

**Pull request merged**
