### PR TITLE
Add CICO build pieces

### PR DESCRIPTION
**Pull request by vpavlin**

### CODE REVIEW

**Comment by fabric8cd** [comment]
@vpavlin snapshot fabric8/fabric8-online-docs:SNAPSHOT-PR-16-1 is available for testing at http://fabric8-online-docs-app-pr-16-fabric8-online-docs.badger.fabric8.io

**Comment by rawlingsj** [comment]
Why is this needed?  The fabric8 pipelines already build the docs + automatically updates the https://github.com/fabric8-apps/fabric8-online-docs-app repo which generate the YAML to deploy as mentioned in the docs.

https://github.com/fabric8io/fabric8-online-docs#deploying-the-documentation-on-openshift

**Comment by rawlingsj** [comment]
This repo is already handled by the fabric8 pipelines, here is the jenkinsfile https://github.com/fabric8io/fabric8-online-docs/blob/master/Jenkinsfile

**Comment by vpavlin** [comment]
@rawlingsj I was asked to get docs running asap. I cannot use generated templates in saas-* repos directly due to tooling limitations. I can fix that in the future, but as I am on PTO next week, I did not want to risk breaking things today, so this was the easiest way to get it up and running.

How about we merge it and I finish the deployment bits and when I am back we revisit how to do deployments using generated templates?

**Comment by rawlingsj** [comment]
No to merging as it's duplicating work, the email thread that I believe you're referring to is not about building the docs it's about where to deploy them..

Where to deploy built OSIO docs:
"yeah we have the docs repo here which have both CI and CD pipelines, on merge to master a docker image is built and released, the pipeline updates the downstream app project which generates the YAML and automatically releases.

that means around 10 mins after a commit to the docs we can just run..

$ export DOCS_VERSION=$(curl -L http://central.maven.org/maven2/io/fabric8/apps/fabric8-online-docs-app/maven-metadata.xml | grep '<latest' | cut -f2 -d">"|cut -f1 -d"<")

$ oc apply -f http://central.maven.org/maven2/io/fabric8/apps/fabric8-online-docs-app/$DOCS_VERSION/fabric8-online-docs-app-$DOCS_VERSION-openshift.yml

so if we deploy to dsaas then I'll add a stage to the app release pipeline to deploy once its released, this follows the same approach as the forge backend."

**Comment by kbsingh** [comment]
👍 to merge, the default build destination is on cico till osio/osio happens, Not willing to put more content in GKE infra that is neither cetrally managed not part of the service itself.

**Comment by rawlingsj** [comment]
> 👍 to merge, the default build destination is on cico till osio/osio happens, Not willing to put more content in GKE infra that is neither cetrally managed not part of the service itself.

With respect I could not disagree more, by duplicating work that is already running using jenkins pipelines + kubernetes you are creating more work and avoiding helping dog food our work.  The builds are already working and have been operational for 5 weeks.  It is not just running on OSIO that makes dogfooding work it is using Jenkins pipelines and kubernetes which we are validating as we go.  Actually having it run on OSIO is the full setup but then next best thing in Jenkins pipelines on Kubernetes which is what we have today on GKE.

**Comment by kbsingh** [comment]
were not using anything more on GKE.  its a dev resource, for a feature team. The service orchestration happens elsewhere, as I've explained to max as well. There are 2 components nominated for the k8s pipelines, beyond that everything else needs to come via the consolidated infra already in place.

-1 to going GKE.

**Comment by rawlingsj** [comment]
so we avoid the Jenkinsfile, loose the snapshot PR feature, go back to manual YAML maintenance rather than the current generated approach we have working here, stop using the jenkins pipelines only until we are running on OSIO?  ummm ok but this seems like an odd approach to working together to help build OSIO with OSIO.  Honestly I'm just a bit disappointed but carry on and ignore the awesome work we've all been putting in.

**Comment by kbsingh** [comment]
@rawlingsj the piece were missing is the GKE infra. all your points are valid, but dont speak through to the concerns raised above. 

For now, @vpavlin @joshuawilson can we get this merged and move forward ?

**Comment by joshuawilson** [comment]
Since @rawlingsj removed his review I can merge it.

**Pull request merged**
