### PR TITLE
First PR for Issue 173

### PR DESCRIPTION
**Pull request by mishaone**
* Updated screenshots and docs.
* Removed SB section and references are now commented out.

### CODE REVIEW

**Comment by mishaone** [comment]
@Preeticp I'd like an extra pair of eyes on this, particularly because the SpringBoot part is now commented out since it doesn't work. Could you have a look at the preview build when it turns up in this issue and merge if it looks okay to you? It already builds and validates, etc so it should be okay but I'd like another person having a look just to be sure nothing is broken.

**Comment by fabric8cd** [comment]
@mishaone snapshot fabric8/fabric8-online-docs:SNAPSHOT-PR-178-1 is available for testing at http://fabric8-online-docs-app-pr-178-fabric8-online-docs.badger.fabric8.io

**Comment by fabric8cd** [comment]
@mishaone snapshot fabric8/fabric8-online-docs:SNAPSHOT-PR-178-2 is available for testing at http://fabric8-online-docs-app-pr-178-fabric8-online-docs.badger.fabric8.io

**Comment by Preeticp** [comment]
@mishaone, all seems good except one mention of the spring boot project in Section 10, seventh bullet point. I have added a commit to remove it to this PR.
Otherwise it builds and validates so nothing seems to be broken.

**Pull request merged**
