### PR TITLE
issue-182

### PR DESCRIPTION
**Pull request by mishaone**
Updated stack reports content.

### CODE REVIEW

**Comment by mishaone** [comment]
Tested locally and builds okay. Waiting for PR build to test and merge.

**Comment by fabric8cd** [comment]
@mishaone snapshot fabric8/fabric8-online-docs:SNAPSHOT-PR-183-2 is available for testing at http://fabric8-online-docs-app-pr-183-fabric8-online-docs.badger.fabric8.io

**Comment by mishaone** [comment]
I added a minor commit to trigger a rebuild which worked okay. Now that it's validated and built correctly, I'll merge this.

**Comment by rkratky** [comment]
@mishaone You should also be able to trigger a rebuild by going to https://jenkins.cd.test.fabric8.io/job/fabric8io-auto-rel/job/fabric8-online-docs/view/change-requests/ -- click 'Build Now' in the context menu that you get by clicking on the little arrow that appears when you hover over a PR (you need to be logged in to the Jenkins instance for the build item to be there).

**Pull request merged**
