### PR TITLE
New structure and contents for e2e doc.

### PR DESCRIPTION
**Pull request by mishaone**
Added new folders, images and primary file to back up in repo. To be reorganized later

### CODE REVIEW

**Comment by rkratky** [comment]
@mishaone, looking at this PR, I'm unsure whether you still want me to set the structure in the repo for the e2e doc. I see you've already set it up, is that correct?

**Comment by mishaone** [comment]
@rkratky- I've just copied over the file structure as I can see it. If you could have a look and confirm I haven't missed out anything important, it would be very useful.

**Comment by rkratky** [comment]
@mishaone, it looks good to me.

**Comment by mishaone** [comment]
@rkratky, I'm breaking this into modules and adding a commit here but it looks like checks are failing. Can you tell me how/where can I see the build for this PR?

**Comment by mishaone** [comment]
@rkratky - since it'll be tomorrow when I next see this, essentially, I want to be able to preview the files in here so far and made changes and see the revised build somewhere that reflects those changes. If you can leave me instructions for that, I'd appreciate it, since this is the first time I'm looking at a complete doc in GH and want to make sure it's coherent and the images work, etc.

**Comment by rkratky** [comment]
@mishaone, AFAICS, the build failures have nothing to do with the content itself.

@rawlingsj, could you please take a look?

**Comment by fabric8cd** [comment]
@mishaone snapshot fabric8/fabric8-online-docs:SNAPSHOT-PR-15-6 is available for testing at http://fabric8-online-docs-app-pr-15-fabric8-online-docs.badger.fabric8.io

**Comment by rawlingsj** [comment]
There were some infra issues which prevented the jobs from passing.  I just re-ran the job and it's working now.

**Comment by mishaone** [comment]
@rawlingsj - excellent, I can see the checks have now passed, which is probably an indicator of the infra issues you mentioned. Thank you for getting this going, and @rkratky for following up.

**Comment by mishaone** [comment]
@rawlingsj the link you posted is the user guide (separate document). Is there anywhere I can see the preview for this PR, which is a different set of content?

**Comment by fabric8cd** [comment]
@mishaone snapshot fabric8/fabric8-online-docs:SNAPSHOT-PR-15-1 is available for testing at http://fabric8-online-docs-app-pr-15-fabric8-online-docs.badger.fabric8.io

**Comment by mishaone** [comment]
@rkratky, maybe you can help figure this out. The link posted above is for the user guide and not the different e2e doc. Is there something missing or some other reason the PR for 15 doesn't include any of the content added in this PR?

**Comment by mishaone** [comment]
@rkratky - reminder for this. Please have a look when you have time. I'd love to stage this to review it myself as a whole and fix up minor things before asking others for review.

**Comment by fabric8cd** [comment]
@mishaone snapshot fabric8/fabric8-online-docs:SNAPSHOT-PR-15-2 is available for testing at http://fabric8-online-docs-app-pr-15-fabric8-online-docs.badger.fabric8.io

**Comment by rkratky** [comment]
@mishaone, let's merge this. I'll then modify the build process to include other docs, too.

**Comment by mishaone** [comment]
Will do, Robert. Merging now.

**Pull request merged**
