### PR TITLE
Issue-92: Changed titles and IDs to gerunds for relevant modules.

### PR DESCRIPTION
**Pull request by mishaone**
Updated titles and IDs for modules to gerunds.

### CODE REVIEW

**Comment by fabric8cd** [comment]
@mishaone snapshot fabric8/fabric8-online-docs:SNAPSHOT-PR-132-1 is available for testing at http://fabric8-online-docs-app-pr-132-fabric8-online-docs.badger.fabric8.io

**Comment by fabric8cd** [comment]
@mishaone snapshot fabric8/fabric8-online-docs:SNAPSHOT-PR-132-3 is available for testing at http://fabric8-online-docs-app-pr-132-fabric8-online-docs.badger.fabric8.io

**Comment by mishaone** [comment]
@rkratky - Can you review this, please. I used the validate and build scripts and the asciidoctor build to test.

Also, I'm a little confused about the dir structure. We seem to have two copied if the modules:

* One is at fabric8-online-docs/docs/e2e_workshop/topics/modules
* The other is at fabric8-online-docs/docs/topics/modules

I'm unsure about which one we should be working in. Could you explain, please?

**Comment by fabric8cd** [comment]
@mishaone snapshot fabric8/fabric8-online-docs:SNAPSHOT-PR-132-4 is available for testing at http://fabric8-online-docs-app-pr-132-fabric8-online-docs.badger.fabric8.io

**Comment by rkratky** [comment]
> Also, I'm a little confused about the dir structure. We seem to have two copied if the modules:
```
    fabric8-online-docs/docs/e2e_workshop/topics/modules
    fabric8-online-docs/docs/topics/modules
```
@mishaone, these are identical -- the first is a symlink to the second.

So, the 'real' directory is `fabric8-online-docs/docs/topics/`, and then there's a symlink to this from both guide directories. Therefore, it doesn't matter 'where' you work because you're always working with the same files. This is how it looks like:
```
$ ls -la docs/

.
..
index.adoc
e2e_workshop/
topics/
user_guide/

$ ls -la docs/e2e_workshop/

.
..
master.adoc
topics -> ../topics/

$ ls -la docs/user_guide/

.
..
master.adoc
topics -> ../topics/
```

**Comment by fabric8cd** [comment]
@mishaone snapshot fabric8/fabric8-online-docs:SNAPSHOT-PR-132-5 is available for testing at http://fabric8-online-docs-app-pr-132-fabric8-online-docs.badger.fabric8.io

**Comment by fabric8cd** [comment]
@mishaone snapshot fabric8/fabric8-online-docs:SNAPSHOT-PR-132-6 is available for testing at http://fabric8-online-docs-app-pr-132-fabric8-online-docs.badger.fabric8.io

**Pull request merged**
