### PR TITLE
issue-248: User preferences changes

### PR DESCRIPTION
**Pull request by mishaone**
* Added new assembly for user preferences 
* Added new modules for user pref
* Added accompanying images

### CODE REVIEW

**Comment by mishaone** [comment]
@rkratky this is the branch where running the asciidoctor build as usual in the user guide directory results in a local build of that doc with no images, just captions:
no_image

**Comment by mishaone** [comment]
I'm going to merge this so I can continue working on stuff in the repo without conflicts. If there is an issue that's not just local for me, we can probably fix it up later.

**Comment by mishaone** [comment]
@rkratky figured it out! My asciidoctor build and rebuild aliases are set to this:
alias adocbuild='asciidoctor --attribute imagesdir=topics/images master.adoc && firefox master.html'

This doesn't correctly specify the images location. The problem was local after all. Sorry for the hassle.

**Comment by mishaone** [comment]
(also including an update for the CONTRIBUTING.md file in the next PR to update the asciidoctor command)

**Comment by rkratky** [comment]
> This doesn't correctly specify the images location. The problem was local after all. Sorry for the hassle.

No problem. I realized what the problem this morning. I forgot to update the build instructions in the CONTRIBUTING, so partially my fault.

**Pull request merged**
